# Load model directly
import itertools
import json
import torch
from sympy.physics.units import temperature
from transformers import AutoTokenizer, AutoModelForCausalLM
import pandas as pd
import re
import os
from openai import OpenAI
import os
import json
import base64
import requests
import jsonlines
import numpy as np

client = OpenAI(
    base_url='https://api.openai.com/v1',
    api_key=' '
)

with open('PhyGenBench/pprompts.json','r') as f:
    data = json.load(f)

result = []
for i in range(len(data)):
    data_tmp = data[i]
    prompt = data_tmp["caption"]
    if isinstance(prompt, dict):
        prompt = json.dumps(prompt, ensure_ascii=False)
    physical_law = data_tmp["physical_laws"]

    Instruction = "You are an expert prompt writer for a physics-aware generative model. Generate a prompt that realistically describe the requested scene."

    Conditions = f"""
        You must produce a prompt that satisfies two conditions:
        1) a realistically plausible scene composition, and
        2) adherence to physical laws
        
        1.Compose a realistically plausible scene that fits the given scene.
          Enrich concrete details about the environment, spatial relationships, lighting, materials, and textures.
          Your task is describe the scene to make video generated by the diffusion model a better performance on simulating the reality. 
          In-context example is provided for your reference, and you need to finish the current task.
          
          ###In-context examples: A tranquil lakeside at sunset. Golden light reflects off the calm water surface, gradually rippling as a gentle breeze passes through. Tall pine trees along the shore sway slightly, their shadows lengthening across the water. A small wooden dock extends into the lake, where a rowboat gently bobs with the subtle movements of the water.
        
        2.For the conceived scene, write the prompt so that it satisfies the specified physical law: {physical_law}.
          To satisfy {physical_law}, reason about how elements should move, interact, and evolve over time throughout the video, without providing formulas. 
          Make physically grounded assumptions explicit and ensure internal consistency.
    
        For your given task, Let’s think step by step.
        """

    Scene = f"Target scene: {prompt}"

    Style = """
        You may include appropriate style keywords such as
        "ultra-realistic", "high fidelity" for photorealistic description,
        "gradually," "suddenly," or "transitions to," for temporal progression,
        "steadycam shot," "zooming in," or "tracking shot," for camera perspective.
        Invent new context-appropriate keywords under each of these three stylistic categories.
        Do NOT list style keywords separately. Incorporate them fluidly into the prose.
        """

    Query = """
        Return ONLY:
        {"prompt": "<one coherent prompt that integrates all conditions and style implicitly>"} 
        """

    msg = Instruction + Conditions + Scene + Style + Query
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {
                "role": "system",
                "content": "You are an assistant that only outputs valid JSON format. Always use double quotes for keys and values, and never use single quotes or any extra text."
            },
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": msg},
                ],
            }
        ],
        max_tokens=512,
    )
    print(response.choices[0].message.content)

    input_string = response.choices[0].message.content

    input_string = input_string.strip().lstrip("```json").rstrip("```").strip()

    try:
        parsed_data = json.loads(input_string)
    except:
        print('except')
        parsed_data = input_string

    print(parsed_data)

    data_tmp['prompt'] = (
    parsed_data.get("prompt")
    if isinstance(parsed_data, dict)
    else str(parsed_data)
)
    result.append(data_tmp)


if __name__ == "__main__":
    print(len(result))

    with open('gprompts2.json', 'w', encoding='utf-8') as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

